### ISSUE TITLE
Error using tableslurp - object has no attribute 'token'

### ISSUE THREAD

**Issue by crania** [JeremyGrosser/tablesnap#62]
I recently installed tablesnap via pip and the copy to S3 process appears to be working - however when I run the tableslurp command I get the following:
Traceback (most recent call last):
  File "/usr/local/bin/tableslurp", line 295, in <module>
    sys.exit(main())
  File "/usr/local/bin/tableslurp", line 291, in main
    dh = DownloadHandler(args)
  File "/usr/local/bin/tableslurp", line 86, in __init__
    (owner, group) = self._build_file_set(args.file)
  File "/usr/local/bin/tableslurp", line 114, in _build_file_set
    bucket = self._get_bucket()
  File "/usr/local/bin/tableslurp", line 105, in _get_bucket
    security_token=self.token)
AttributeError: 'DownloadHandler' object has no attribute 'token'

I set AWS_SECURITY_TOKEN= in the environment but not clear if there are additional steps I am missing (such as using STS to get a token for the requests?).

My command is basically this:
tableslurp -n server.localdomain  bucket /mnt/cassandra/data /mnt/cassandra/data

I tried an upgrade via pip but no luck yet. 

Appreciate the help.

**Comment by crania** [comment]
Hey - I saw a similar issue somewhere and cloned the repo and ran setup.py (instead of pip) - that seemed to apply a fix.
