### ISSUE TITLE
tablesnap crash II - SSLError: [Errno 8] _ssl.c:490: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by jwojcik** [JeremyGrosser/tablesnap#65]
2015-10-23 11:38:52,420 INFO Performing multipart upload for /opt/cassandra/dataXXX_production/service_last_downloads/XXX_production-service_last_downloads-ic-8588-Index.db
2015-10-23 11:45:53,206 INFO Error uploading part 1
2015-10-23 11:45:53,457 CRITICAL Failed to upload file contents.
2015-10-23 11:45:53,526 ERROR Error uploading prod-cass-r01.ihost.XXX.com:/opt/cassandra/data/XXX_production/service_last_downloads/XXX_production-service_last_downloads-ic-8588-Index.db
Traceback (most recent call last):
  File "/usr/bin/tablesnap", line 349, in upload_sstable
    mp.upload_part_from_file(chunk, part)
  File "/usr/lib/python2.6/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
SSLError: [Errno 8] _ssl.c:490: EOF occurred in violation of protocol

2015-10-23 11:45:53,526 CRITICAL Failed uploading /opt/cassandra/data/XX/service_last_downloads/XXX_production-service_last_downloads-ic-8588-Index.db. Aborting.
Traceback (most recent call last):
  File "/usr/bin/tablesnap", line 123, in worker
    self.upload_sstable(bucket, keyname, f)
  File "/usr/bin/tablesnap", line 349, in upload_sstable
    mp.upload_part_from_file(chunk, part)
  File "/usr/lib/python2.6/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
SSLError: [Errno 8] _ssl.c:490: EOF occurred in violation of protocol

**Comment by JeremyGrosser** [comment]
Not sure what's causing your SSL errors... Could be an intermittent S3 issue or your libssl is outdated. Either way, there's not much we can do about this. If you'd like the client to retry upload attempts, add the --retries option.
