### ISSUE TITLE
Tablesnap crash III - INFO Error uploading part 28 / error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by jwojcik** [JeremyGrosser/tablesnap#66]
2015-11-02 09:30:23,951 INFO Error uploading part 28
2015-11-02 09:30:24,165 CRITICAL Failed to upload file contents.
2015-11-02 09:30:24,239 ERROR Error uploading servername:/opt/cassandra/data/keyspace/tablenameXXX-ic-6261-Data.db
Traceback (most recent call last):
  File "/usr/bin/tablesnap", line 349, in upload_sstable
    mp.upload_part_from_file(chunk, part)
  File "/usr/lib/python2.6/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer

2015-11-02 09:30:24,239 CRITICAL Failed uploading /opt/cassandra/data/keyspace/tablenameXXX-ic-6261-Data.db. Aborting.
Traceback (most recent call last):
  File "/usr/bin/tablesnap", line 123, in worker
    self.upload_sstable(bucket, keyname, f)
  File "/usr/bin/tablesnap", line 349, in upload_sstable
    mp.upload_part_from_file(chunk, part)
  File "/usr/lib/python2.6/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer

**Comment by aimanparvaiz** [comment]
Yep, facing the same issue.

**Comment by sharathm** [comment]
Same here..

**Comment by JeremyGrosser** [comment]
Upload retries are now supported. Add --retries to your tablesnap call to enable it.
